packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.9.3
  '@orpc/openapi': ^1.9.3
  '@orpc/server': ^1.9.3
  '@orpc/zod': ^1.9.3
  better-auth: ^1.3.27
  dotenv: ^17.2.3
  drizzle-orm: ^0.44.6
  hono: ^4.9.11
  tsdown: ^0.15.6
  typescript: ^5.9.3
  vitest: 2.1.9
  zod: ^4.1.12
