packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.9.4
  '@orpc/openapi': ^1.9.4
  '@orpc/server': ^1.9.4
  '@orpc/zod': ^1.9.4
  better-auth: ^1.3.27
  dotenv: ^17.2.3
  drizzle-orm: ^0.44.6
  hono: ^4.9.12
  tsdown: ^0.15.7
  typescript: ^5.9.3
  vitest: 3.2.4
  zod: ^4.1.12
