packages:
  - apps/*
  - packages/*
catalog:
  "@orpc/server": ^1.9.0
  "@orpc/openapi": ^1.9.0
  "@orpc/zod": ^1.9.0
  better-auth: ^1.3.13
  dotenv: ^17.2.2
  hono: ^4.8.2
  zod: ^4.1.11
  typescript: ^5.8.2
  tsdown: ^0.15.5
  "@orpc/client": ^1.9.0
